### ISSUE TITLE
Failed to build solution in VS2022

### ISSUE THREAD

**Issue by RohanFernandez** [NVIDIAGameWorks/Falcor#365]
On making a build out of the box, I get several errors with 6.0-preview2 Pre-release

(It however builds and runs properly when I use the Falcor 6.0-preview commit 17Feb2023 with VS2019. Similarly with the same commit it runs with VS2022 but I still get errors in the build.)

When attempting to build 6.0-preview2 Pre-release, 
To test I deleted 'packman-repo', deleted my local repository and cloned it again, clicked on setup_vs2022.bat,
opened the solution with vs2022 and built the solution.
I get the following

Error	C1001	Internal compiler error.	AssimpImporter	
Falcor\external\fmt\include\fmt\ostream.h	32	

Error	D8040	error creating or communicating with child process	FalcorTest	
Falcor\build\windows-vs2022\Source\Tools\FalcorTest\cl	1	

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

40>INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\CL.exe'
40>    Please choose the Technical Support command on the Visual C++
40>    Help menu, or open the Technical Support help file for more information
49>   Creating library /Falcor/build/windows-vs2022/Source/RenderPasses/AccumulatePass/Debug/AccumulatePass.lib and object /Falcor/build/windows-vs2022/Source/RenderPasses/AccumulatePass/Debug/AccumulatePass.exp
40>MERLFileTests.cpp
40>CastFloat16.cpp
47>   Creating library /Falcor/build/windows-vs2022/Source/RenderPasses/BSDFViewer/Debug/BSDFViewer.lib and object /Falcor/build/windows-vs2022/Source/RenderPasses/BSDFViewer/Debug/BSDFViewer.exp
40>Float16Tests.cpp
40>Float64Tests.cpp
48>Done building project "AssimpImporter.vcxproj" -- FAILED.
40>\Falcor\external\fmt\include\fmt/ostream.h(32,1): fatal  error C1001: Internal compiler error.

42>ErrorMeasurePass.vcxproj -> \Falcor\build\windows-vs2022\bin\Debug\plugins\ErrorMeasurePass.dll
47>BSDFViewer.vcxproj -> \Falcor\build\windows-vs2022\bin\Debug\plugins\BSDFViewer.dll
49>AccumulatePass.vcxproj -> \Falcor\build\windows-vs2022\bin\Debug\plugins\AccumulatePass.dll
40>cl : command line  error D8040: error creating or communicating with child process
30>PixelInspectorPass.vcxproj -> \Falcor\build\windows-vs2022\bin\Debug\plugins\PixelInspectorPass.dll
50>------ Build started: Project: FalcorPython, Configuration: Debug x64 ------
40>Done building project "FalcorTest.vcxproj" -- FAILED.

**Comment by RohanFernandez** [comment]
@skallweitNV 
Thanks! Apparently updating Visual Studio was the fix.
It works with the VS 2022 17.6.4 version.
